### ISSUE TITLE
Judge Service is hanging (to analyse)

### ISSUE THREAD

**Issue by spolnik** [spolnik/JAlgoArena#37]
[2017_05_02_hanging_judge_service.zip](https://github.com/spolnik/JAlgoArena/files/753226/2017_05_02_hanging_judge_service.zip)
[judge.zip.005.zip](https://github.com/spolnik/JAlgoArena/files/753231/judge.zip.005.zip)
[judge.zip.006.zip](https://github.com/spolnik/JAlgoArena/files/753232/judge.zip.006.zip)
[judge.zip.007.zip](https://github.com/spolnik/JAlgoArena/files/753233/judge.zip.007.zip)
[judge.zip.001.zip](https://github.com/spolnik/JAlgoArena/files/753234/judge.zip.001.zip)
[judge.zip.002.zip](https://github.com/spolnik/JAlgoArena/files/753235/judge.zip.002.zip)
[judge.zip.003.zip](https://github.com/spolnik/JAlgoArena/files/753236/judge.zip.003.zip)
[judge.zip.004.zip](https://github.com/spolnik/JAlgoArena/files/753230/judge.zip.004.zip)

**Comment by spolnik** [comment]
The dump is not that useful, it does not indicate we are even close to the heap max size - one of advices would be to add:
- `-XX:+HeapDumpOnOutOfMemoryError`
- if it's really about GC running too many times, and it's kind of possible because we load and unload from JVM the solutions code - adding `-XX:-UseGCOverheadLimit` may be a solution (see [Oracle Docs](https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/memleaks002.html)) 
- another worth to mention thing is, it's failing on Eureka Client stuff, the stack trace is

`java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at com.sun.jersey.api.uri.UriBuilderImpl.appendPath(UriBuilderImpl.java:571)
	at com.sun.jersey.api.uri.UriBuilderImpl.appendPath(UriBuilderImpl.java:542)
	at com.sun.jersey.api.uri.UriBuilderImpl.path(UriBuilderImpl.java:267)
	at com.sun.jersey.api.client.WebResource.path(WebResource.java:396)
	at com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient.getApplicationsInternal(AbstractJerseyEurekaHttpClient.java:187)
	at com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient.getDelta(AbstractJerseyEurekaHttpClient.java:170)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$7.execute(EurekaHttpClientDecorator.java:152)
	at com.netflix.discovery.shared.transport.decorator.MetricsCollectingEurekaHttpClient.execute(MetricsCollectingEurekaHttpClient.java:73)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getDelta(EurekaHttpClientDecorator.java:149)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$7.execute(EurekaHttpClientDecorator.java:152)
	at com.netflix.discovery.shared.transport.decorator.RedirectingEurekaHttpClient.execute(RedirectingEurekaHttpClient.java:89)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getDelta(EurekaHttpClientDecorator.java:149)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$7.execute(EurekaHttpClientDecorator.java:152)
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:119)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getDelta(EurekaHttpClientDecorator.java:149)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$7.execute(EurekaHttpClientDecorator.java:152)
	at com.netflix.discovery.shared.transport.decorator.SessionedEurekaHttpClient.execute(SessionedEurekaHttpClient.java:77)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getDelta(EurekaHttpClientDecorator.java:149)
	at com.netflix.discovery.DiscoveryClient.getAndUpdateDelta(DiscoveryClient.java:1064)
	at com.netflix.discovery.DiscoveryClient.fetchRegistry(DiscoveryClient.java:946)
	at com.netflix.discovery.DiscoveryClient.refreshRegistry(DiscoveryClient.java:1468)
	at com.netflix.discovery.DiscoveryClient$CacheRefreshThread.run(DiscoveryClient.java:1435)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`
